### ISSUE TITLE
章节6幻灯片符号错误

### ISSUE THREAD

**Issue by windowsair** [Kivy-CN/HandsOnOpenCL_CN#1]
章节6第23张幻灯片其中`"\nUsing OpenCL Device ”`右边引号错误

**Comment by cycleuser** [comment]
感谢指出！已经修正。
这是原版中代码内容里面就有的这样一个错误，刚刚检查了一下发现第五章中也有这一样的错误。
已经将翻译版当中的此处错误进行了修改，但原版中的就不做改动了，保持原版原样了。
再次感谢！
我都没想到会有人来看这个系列。
